@extends('layouts.policy')

@section('title', 'Privacy Policy')

@section('content')
    <div class="card">
        <p class="meta">App: Zalawadi Sai Suthar &middot; Last updated: June 03, 2026</p>

        <p class="lead">
            This Privacy Policy describes the policies and procedures of <strong>Zalawadi Sai Suthar</strong>
            (the &ldquo;Application&rdquo;) regarding the collection, use and disclosure of your information when
            you use the Application, and tells you about your privacy rights and how the law protects you.
        </p>
        <p>
            We use your Personal Data to provide and improve the Application. By using the Application, you agree
            to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2>Interpretation and Definitions</h2>

        <h3>Interpretation</h3>
        <p>
            The words whose initial letters are capitalized have meanings defined under the following conditions.
            The following definitions shall have the same meaning regardless of whether they appear in singular or
            in plural.
        </p>

        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
            <li><strong>Account</strong> means a unique account created for you to access the Application or parts of the Application.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &ldquo;control&rdquo; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Application</strong> refers to <strong>Zalawadi Sai Suthar</strong>, the software program provided by the Company.</li>
            <li><strong>Company</strong> (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or &ldquo;Our&rdquo; in this Privacy Policy) refers to <strong>Zalawadi Sai Suthar</strong>.</li>
            <li><strong>Country</strong> refers to: Gujarat, India.</li>
            <li><strong>Device</strong> means any device that can access the Application, such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> (or &ldquo;Personal Information&rdquo;) is any information that relates to an identified or identifiable individual. We use &ldquo;Personal Data&rdquo; and &ldquo;Personal Information&rdquo; interchangeably unless a law uses a specific term.</li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Application, to provide the Application on behalf of the Company, to perform services related to the Application, or to assist the Company in analyzing how the Application is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Application or from the Application infrastructure itself (for example, the duration of a session).</li>
            <li><strong>You</strong> means the individual accessing or using the Application, or the company, or other legal entity on behalf of which such individual is accessing or using the Application, as applicable.</li>
        </ul>

        <h2>Collecting and Using Your Personal Data</h2>

        <h3>Types of Data Collected</h3>

        <h4>Personal Data</h4>
        <p>
            While using the Application, we may ask you to provide us with certain personally identifiable information
            that can be used to contact or identify you. Personally identifiable information may include, but is not
            limited to:
        </p>
        <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
        </ul>

        <h4>Usage Data</h4>
        <p>
            Usage Data is collected automatically when using the Application. Usage Data may include information such
            as your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of
            the Application that you visit, the time and date of your visit, the time spent on those pages, unique
            device identifiers and other diagnostic data.
        </p>
        <p>
            When you access the Application by or through a mobile device, we may collect certain information
            automatically, including, but not limited to, the type of mobile device you use, your mobile device's
            unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet
            browser you use, unique device identifiers and other diagnostic data.
        </p>

        <h4>Information Collected while Using the Application</h4>
        <p>
            While using the Application, in order to provide features of the Application, we may collect, with your
            prior permission:
        </p>
        <ul>
            <li>Pictures and other information from your Device's camera and photo library</li>
        </ul>
        <p>
            We use this information to provide features of the Application, and to improve and customize the
            Application. The information may be uploaded to the Company's servers and/or a Service Provider's server,
            or it may be simply stored on your Device.
        </p>
        <p>
            You can enable or disable access to this information at any time through your Device settings.
        </p>

        <h3>Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
            <li><strong>To provide and maintain the Application</strong>, including to monitor the usage of the Application.</li>
            <li><strong>To manage Your Account:</strong> to manage your registration as a user of the Application. The Personal Data you provide can give you access to different functionalities of the Application that are available to you as a registered user.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with us through the Application.</li>
            <li><strong>To contact You:</strong> to contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which we offer that are similar to those that you have already purchased or inquired about, unless you have opted not to receive such information.</li>
            <li><strong>To manage Your requests:</strong> to attend and manage your requests to us.</li>
            <li><strong>For business transfers:</strong> we may use your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by us about our Application users is among the assets transferred.</li>
            <li><strong>For other purposes:</strong> we may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve the Application, products, services, marketing and your experience.</li>
        </ul>

        <h3>Sharing of Your Personal Data</h3>
        <p>We may share your Personal Data in the following situations:</p>
        <ul>
            <li><strong>With Service Providers:</strong> we may share your Personal Data with Service Providers to monitor and analyze the use of the Application, and to contact you.</li>
            <li><strong>For business transfers:</strong> we may share or transfer your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
            <li><strong>With Affiliates:</strong> we may share your Personal Data with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners or other companies that we control or that are under common control with us.</li>
            <li><strong>With business partners:</strong> we may share your Personal Data with our business partners to offer you certain products, services or promotions.</li>
            <li><strong>With other users:</strong> if the Application offers public areas, when you share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
            <li><strong>With Your consent:</strong> we may disclose your Personal Data for any other purpose with your consent.</li>
        </ul>

        <h3>Retention of Your Personal Data</h3>
        <p>
            The Company will retain your Personal Data only for as long as is necessary for the purposes set out in
            this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your data to comply with applicable laws),
            resolve disputes, and enforce our legal agreements and policies.
        </p>
        <p>
            Where possible, we apply shorter retention periods and/or reduce identifiability by deleting, aggregating,
            or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (&ldquo;up
            to&rdquo;) and we may delete or anonymize data sooner when it is no longer needed for the relevant
            purpose. We apply different retention periods to different categories of Personal Data based on the purpose
            of processing and legal obligations:
        </p>
        <ul>
            <li><strong>Account Information:</strong> user accounts are retained for the duration of your account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.</li>
            <li><strong>Customer Support Data:</strong> support tickets and correspondence are retained up to 24 months from the date of ticket closure to resolve follow-up inquiries, track service quality, and defend against potential legal claims. Chat transcripts are retained up to 24 months for quality assurance and staff training purposes.</li>
            <li><strong>Usage Data:</strong> application usage statistics are retained up to 24 months to understand feature adoption and service improvements. Server logs (IP addresses, access times) are retained up to 24 months for security monitoring and troubleshooting purposes.</li>
        </ul>
        <p>
            Usage Data is retained in accordance with the retention periods described above, and may be retained longer
            only where necessary for security, fraud prevention, or legal compliance.
        </p>
        <p>We may retain Personal Data beyond the periods stated above for different reasons:</p>
        <ul>
            <li><strong>Legal obligation:</strong> we are required by law to retain specific data (e.g., financial records for tax authorities).</li>
            <li><strong>Legal claims:</strong> data is necessary to establish, exercise, or defend legal claims.</li>
            <li><strong>Your explicit request:</strong> you ask us to retain specific information.</li>
            <li><strong>Technical limitations:</strong> data exists in backup systems that are scheduled for routine deletion.</li>
        </ul>
        <p>You may request information about how long we will retain your Personal Data by contacting us.</p>
        <p>When retention periods expire, we securely delete or anonymize Personal Data according to the following procedures:</p>
        <ul>
            <li><strong>Deletion:</strong> Personal Data is removed from our systems and no longer actively processed.</li>
            <li><strong>Backup retention:</strong> residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule, and are not restored except where necessary for security, disaster recovery, or legal compliance.</li>
            <li><strong>Anonymization:</strong> in some cases, we convert Personal Data into anonymous statistical data that cannot be linked back to you. This anonymized data may be retained indefinitely for research and analytics.</li>
        </ul>

        <h3>Transfer of Your Personal Data</h3>
        <p>
            Your information, including Personal Data, is processed at the Company's operating offices and in any other
            places where the parties involved in the processing are located. This means that this information may be
            transferred to &mdash; and maintained on &mdash; computers located outside of your state, province, country
            or other governmental jurisdiction where the data protection laws may differ from those from your
            jurisdiction.
        </p>
        <p>
            Where required by applicable law, we will ensure that international transfers of your Personal Data are
            subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all
            steps reasonably necessary to ensure that your data is treated securely and in accordance with this
            Privacy Policy, and no transfer of your Personal Data will take place to an organization or a country
            unless there are adequate controls in place including the security of your data and other personal
            information.
        </p>

        <h3>Delete Your Personal Data</h3>
        <p>
            You have the right to delete or request that we assist in deleting the Personal Data that we have
            collected about you. The Application may give you the ability to delete certain information about you from
            within the Application.
        </p>
        <p>
            You may update, amend, or delete your information at any time by signing in to your Account, if you have
            one, and visiting the account settings section that allows you to manage your personal information. You
            may also contact us to request access to, correct, or delete any Personal Data that you have provided to
            us.
        </p>
        <p>
            Please note, however, that we may need to retain certain information when we have a legal obligation or
            lawful basis to do so.
        </p>

        <h3>Disclosure of Your Personal Data</h3>

        <h4>Business Transactions</h4>
        <p>
            If the Company is involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
            We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy
            Policy.
        </p>

        <h4>Law enforcement</h4>
        <p>
            Under certain circumstances, the Company may be required to disclose your Personal Data if required to do
            so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
        </p>

        <h4>Other legal requirements</h4>
        <p>The Company may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Application</li>
            <li>Protect the personal safety of users of the Application or the public</li>
            <li>Protect against legal liability</li>
        </ul>

        <h3>Security of Your Personal Data</h3>
        <p>
            The security of your Personal Data is important to us, but remember that no method of transmission over
            the Internet, or method of electronic storage is 100% secure. While we strive to use commercially
            reasonable means to protect your Personal Data, we cannot guarantee its absolute security.
        </p>

        <h2>Children's Privacy</h2>
        <p>
            The Application does not address anyone under the age of 16. We do not knowingly collect personally
            identifiable information from anyone under the age of 16. If you are a parent or guardian and you are
            aware that your child has provided us with Personal Data, please contact us. If we become aware that we
            have collected Personal Data from anyone under the age of 16 without verification of parental consent, we
            take steps to remove that information from our servers.
        </p>
        <p>
            If we need to rely on consent as a legal basis for processing your information, and your country requires
            consent from a parent, we may require your parent's consent before we collect and use that information.
        </p>

        <h2>Links to Other Websites</h2>
        <p>
            The Application may contain links to other websites that are not operated by us. If you click on a third
            party link, you will be directed to that third party's site. We strongly advise you to review the Privacy
            Policy of every site you visit.
        </p>
        <p>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any
            third party sites or services.
        </p>

        <h2>Changes to this Privacy Policy</h2>
        <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
            Privacy Policy on this page.
        </p>
        <p>
            We will let you know via email and/or a prominent notice on the Application, prior to the change becoming
            effective and update the &ldquo;Last updated&rdquo; date at the top of this Privacy Policy.
        </p>
        <p>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
            are effective when they are posted on this page.
        </p>

        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, you can contact us:</p>
        <ul>
            <li>By email: <a href="mailto:zalawadisaisuthartrustsurat5@gmail.com">zalawadisaisuthartrustsurat5@gmail.com</a></li>
            <li>By phone: 8200822875</li>
        </ul>
    </div>
@endsection
